import Vue from "vue";
import Element, { Button } from "element-ui";
import "element-ui/lib/theme-chalk/index.css";
import { Form, FormItem } from "element-ui";
import { Input } from "element-ui";
Vue.use(Element);
Vue.use(Button);
Vue.use(FormItem);
Vue.use(Form);
Vue.use(Input);
